services:
  run-test:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /opt/
  clean:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /opt/
    entrypoint: ['rm', '-rf', 'env-main', 'out-main', 'env-main','out-main', 'travis-blogdown']