services:
  run-test:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /opt/
  clean:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /opt/
    entrypoint: ['sh', '/root/clean.sh']